name: Tests
run-name: Running tests for push by ${{ github.actor }}
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: python3 test/tests.py

  static-analysis:
    steps:
      - uses: actions/checkout@main
      - uses: jakebailey/pyright-action@v2.3.2
      - run: pyright .
